name: tickets-deploy

on:
  push:
    branches: [master]
    paths:
      - "tickets/**"

env:
  IBM_CLOUD_API_KEY: ${{secrets.IBM_CLOUD_API_KEY}}
  IBM_CLOUD_REGION: eu-de
  IMAGE_NAME: tickets
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY_HOSTNAME: de.icr.io
  ICR_NAMESPACE: ticketing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f kubernetes-service
          ibmcloud plugin install -f container-registry
        # Authenticate with IBM Cloud CLI
      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}"
          ibmcloud cr region-set "${IBM_CLOUD_REGION}"
          ibmcloud cr login
          # Build the Docker image
      - name: Build with Docker
        run: |
          cd tickets
          docker build -t "$REGISTRY_HOSTNAME"/"$ICR_NAMESPACE"/"$IMAGE_NAME" --build-arg GITHUB_SHA="$GITHUB_SHA" --build-arg GITHUB_REF="$GITHUB_REF" .
      # Push the image to IBM Container Registry
      - name: Push the image to ICR
        run: |
          docker push $REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME
