name: tests-tickets

on:
  push:
    branches: [master]
    paths:
      - "tickets/**"
  pull_request:
    branches: [master]
    paths:
      - "tickets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd tickets && npm install && npm run test:ci
